# Generated by Django 4.0.3 on 2022-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0002_schedule_room_room_name_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='вместимость аудитори'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название аудитории'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(verbose_name='конец сессии'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(max_length=100, verbose_name='название аудитории'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(verbose_name='старт сессии'),
        ),
    ]
