# Generated by Django 4.0.3 on 2022-03-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0003_alter_room_capacity_alter_room_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomend.room'),
        ),
    ]
