# Generated by Django 4.0.3 on 2022-03-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0004_alter_schedule_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end',
            new_name='finish',
        ),
    ]
