# Generated by Django 4.0.3 on 2022-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0006_alter_room_options_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finish',
            field=models.DateTimeField(verbose_name='Конец сессии'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(verbose_name='Старт сессии'),
        ),
    ]
